version: '3.9'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8000:80
      - 44300:443
    volumes:
      - ./nginx/config:/etc/nginx/conf.d
#      - ./nginx/certificates:/etc/ssl/private
    networks:
       - local

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
    - "8080:80"
    - "5341"
    networks: 
      - local

  core.identityprovider:
    image: ${DOCKER_REGISTRY-}coreidentityprovider
    container_name: identityprovider
    build:
      context: .
      dockerfile: Core.IdentityProvider/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks: 
      - local

  core.frontend:
    image: ${DOCKER_REGISTRY-}corefrontendcontainer
    container_name: frontendcontainer
    build:
      context: .
      dockerfile: Core.FrontEnd.Container/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8081:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks: 
      - local
  
networks:
  local:

